package org.yl.ims.util.dbUtil.dialect;

public class PostgreSQLDialect extends Dialect {
	public PostgreSQLDialect() {
		super();
		defaultJDBCType.put(Boolean.class, "BOOLEAN");
		defaultJDBCType.put(boolean.class, "BOOLEAN");
		defaultJDBCType.put(String.class, "TEXT");
	}

	public String autoGeneratedValue() {
		return "";
	}

	@Override
	public String getCatalog() {
		return null;
	}
	@Override
	public boolean isColumnNameQuoted() {
		return true;
	}
	@Override
	public String getSchema() {
		return "public";
	}
}
